version: "3.5"
services:
  question-generator-client:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      SERVICE_4200_NAME: QuizMaster
    networks: 
      - question-generator-client-network
    ports:
      - "4200:4200"
    volumes:
      - ".:/QuizRT/usr/src/app"
      - /QuizRT/usr/src/app/node_modules
networks:
  question-generator-client-network:
    name: quizrt-network
    external: true